### ISSUE TITLE
menuarrow may be covered under certain circumstances

### ISSUE THREAD

**Issue by yfdyh000** [darktrojan/menufilter#12]
View a menu with "menuarrow" and no scrollbar (like the Tools menu), open Developer Tools to squeeze page height, and then select the Bookmarks menu, then select Tools menu.

![2015-10-07 23 10 03](https://cloud.githubusercontent.com/assets/1769875/10341743/8f0b67fc-6d48-11e5-9636-036909b91943.png)

**Comment by darktrojan** [comment]
Okay, I see this and I can fix it, but because it is XUL and XUL is stupid, I have to do something odd to fix it. :-(
