### ISSUE TITLE
context-navigation.label can't reload after reinstall xpi

### ISSUE THREAD

**Issue by yfdyh000** [darktrojan/menufilter#14]
Modify the context-navigation.label in xpi file, reinstall it, reopen about:menufilter page, the label has not been refreshed until you restart your browser.

I've tried remove the defineLazyGetter, but it seems no effect.

**Comment by darktrojan** [comment]
There's a cache that probably doesn't get emptied unless the add-on version number changes. I think `nglayout.debug.disable_xul_cache = true` is the setting which controls it.

**Comment by yfdyh000** [comment]
I think this will not cache non-XUL files.

**Comment by darktrojan** [comment]
I must have the wrong one. Anyway, my point was that it's a Firefox bug ([this one](https://bugzilla.mozilla.org/show_bug.cgi?id=918033)) not a Menu Filter problem.
