### ISSUE TITLE
"Tab Context Menu" category blank

### ISSUE THREAD

**Issue by anewuser** [darktrojan/menufilter#15]
I  get this on Firefox 42 64-bit running on Windows 10. 

![screenshot](https://cloud.githubusercontent.com/assets/6733770/11091210/78b0b4d0-885f-11e5-8f52-9259f59bb9e6.png)

Is this category displayed normally for you? I also have Tab Mix Plus and other extensions installed, so maybe it's some incompatibility.

**Comment by darktrojan** [comment]
Works for me with TMP installed. Is there anything that looks related on the Browser Console?

**Comment by anewuser** [comment]
I've done some testing and found out that this really only happens when TMP is enabled. The console doesn't show anything.

Here is my TMP preferences file: [TMPpref.txt](https://gist.github.com/anewuser/0be3820255ae1b96720c).

**Comment by darktrojan** [comment]
I couldn't see this before because the menu is slightly different in Firefox >43. Will release a fixed version soon.

**Comment by anewuser** [comment]
Thank you. :)

**Comment by anewuser** [comment]
I've just noticed that the "Undo Close Tab" item isn't hidden from the tab bar context menu even after I disable it with Menu Filter.

**Comment by darktrojan** [comment]
Ohhh, I see what you're on about. That's a different context menu. It's not on the Menu Filter config page because there's so few items on it.
