### ISSUE TITLE
"Bookmarks Context Menu" doesn't affect Library on Firefox 42

### ISSUE THREAD

**Issue by anewuser** [darktrojan/menufilter#16]
I've hidden some entries from the "Bookmarks Context Menu" category, like the "Open in a New Window" item, but I still see them when I open the Firefox Library (chrome://browser/content/places/places.xul) on Firefox 42 for Windows.

**Comment by darktrojan** [comment]
Huh, I thought I'd already fixed that. Apparently not. I have now.

**Comment by anewuser** [comment]
Thank you.

**Comment by anewuser** [comment]
I got the update today, but the items still show up even after a browser restart:

![Screenshot](https://cloud.githubusercontent.com/assets/6733770/11452846/2d0d6b4c-95dc-11e5-8d13-f8ee26845131.png)
