### ISSUE TITLE
Internal pages opened as tabs do not have menus filtered

### ISSUE THREAD

**Issue by anewuser** [darktrojan/menufilter#17]
I'm sorry for opening another issue, but I think that maybe you don't receive notifications for new posts on issues after closing them. I've left a comment on #15 reporting a problem with the Tab Context Menu that still exists (at least when used along with Tab Mix Plus on Firefox 42 for Windows):

> "Undo Close Tab" item isn't hidden from the tab bar context menu even after I disable it with Menu Filter.

I assume you didn't see it because you've replied  to #16, which was posted after that. Anyway, after the fix for #16, it still shows all Library menu entries to me:

> I got the update today, but the items still show up even after a browser restart:
> 
> ![Screenshot](https://cloud.githubusercontent.com/assets/6733770/11452846/2d0d6b4c-95dc-11e5-8d13-f8ee26845131.png)

I'm not the only one who can't hide these entries. [A user on Reddit](https://www.reddit.com/r/firefox/comments/3uitah/menu_filter_lightweight_extension_to_make_remove/) said that he tried your extension but uninstalled it because "Open All in Tabs" and other items didn't work.

Note: If Menu Filter 12 was released before that fix, ignore the second part of this post.

**Comment by darktrojan** [comment]
I've seen them, just have other priorities at the moment. FWIW, I haven't managed to reproduce either.

**Comment by anewuser** [comment]
I've tested it with all other add-ons disabled, but the result was the same as what's shown in the previous screenshot. Is there anything else I can do to help you figure out what the problem is?

**Comment by darktrojan** [comment]
Does hiding the items have the right effect on the main Firefox window? That is, when you right-click on something on the bookmarks menu or toolbar?

Also, you could open the browser console and see if any messages show up when you do something, particularly when you show/hide items in the Menu Filter options.

Last thing I can think of is to start a fresh Firefox profile, install Menu Filter, and see what happens then.

**Comment by anewuser** [comment]
The bookmarks bar and other context menus are affected as expected, but the Library isn't. There are no errors in the console. I finally tried it on a Virtual Machine running Windows XP and the Library wasn't affected either.

Are you sure that you can now hide items from the context menu for bookmarks at chrome://browser/content/places/places.xul on Firefox 42?

**Comment by darktrojan** [comment]
Are you opening the library by visiting that URL in the browser window‽

**Comment by anewuser** [comment]
Yes. I keep my bookmarks bar hidden and use that address to access the library. That's why I mentioned it in my first post.

**Comment by darktrojan** [comment]
Well that explains it. Menu Filter only works with windows, not windows opened as pages (although now that I've seen the library opened as a page, I kinda like it). That'll probably take some serious hack-job to fix, so it may be some time before I fix it.

**Comment by anewuser** [comment]
I keep it as a bookmark and just start typing out "places" to open it.  I didn't consider that to be a problem because other extensions that affect the Library work normally when I open it like that. 

I also use [Download Manager Tweak](https://addons.mozilla.org//firefox/addon/download-manager-tweak/) to open the built-in download manager in a new tab when I click on the download button.
