### ISSUE TITLE
Changelog opens in Thunderbird addons repository instead of Firefox's

### ISSUE THREAD

**Issue by anewuser** [darktrojan/menufilter#21]
The "What changed?" button on the Menu Filter 15 update notification for Firefox  45.0.2 opens https://addons.mozilla.org/en-US/thunderbird/addon/menu-filter/versions/?page=1#version-15 instead of https://addons.mozilla.org/firefox/addon/menu-filter/versions/?page=1#version-15

**Comment by yfdyh000** [comment]
https://github.com/darktrojan/menufilter/search?q=CHANGELOG_URL&type=Code looks good.

**Comment by anewuser** [comment]
@yfdyh000 It must have been a problem on the Mozilla server then.

**Comment by anewuser** [comment]
That button opened the correct page after updating to "Version 16".
