### ISSUE TITLE
Bookmarks & History Button Menus

### ISSUE THREAD

**Issue by beautypersoni** [darktrojan/menufilter#3]
Hello! First off, awesome add-on, Geoff! Just finished doing a review of it on the Firefox page. Coming here I discovered you also created New Tab Tools, which I also recently started using, which then led to me installing Undo Close Tab. Your on a roll!

That said, I've found one little hiccup with Menu Filter. Some of the items I hid in the bookmarks and history menus still show up in the toolbar icon versions of those menus - i.e. the menus from the icons I moved onto the address bar from the customize menu.

This issue doesn't really affect me much at all since I previously used Menu Editor, which didn't work at all with those two menus, but I though I'd point it out.

(I only use Firefox's address bar, to which I added the bookmarks, history and "share this page" icons, and the few bookmark icons I use, which I moved from my hidden bookmark toolbar. I also keep the actual menu bar hidden, since the items I keep in the new customizable Firefox menu are all I usually need.)

Anyhoo...

**Comment by darktrojan** [comment]
That turned out to be an easy fix, but it was stupidly hard to figure out what I needed to do. Thanks for the suggestion.

**Comment by beautypersoni** [comment]
Awesome! Keep rolling, Geoff! :^D
