### ISSUE TITLE
restore closed tabs in panel history and some others

### ISSUE THREAD

**Issue by heforfree** [darktrojan/menufilter#4]
hi
thankyou so much for your addon
if you can add restore closed tabs in panel history to  hide  it

**Comment by heforfree** [comment]
and
hide open all in private tabs -rightclick on folder in bookmark toolbar ,maybe it is for Private Tab addon
hide open all in tabs at the end of folder in bookmark folder

**Comment by darktrojan** [comment]
@heforfree Please make another issue about the second comment if you still want it. I can't promise to fix it though because it's complicated.

**Comment by heforfree** [comment]
no problem thank you for update
